### ISSUE TITLE
Extra span tags in paragraphs

### ISSUE THREAD

**Issue by Bluejay47** [jaredreich/pell#153]
Pell seems to be putting extra span tags with font-size formatting in paragraphs tags. Did I do something to cause this, is it a bug, or intentional? If it is intentional is there someway to disable this?

```
<span style="font-size: 16.4044px;">[misc. text]</span>
```

Thanks.

**Comment by dvtan** [comment]
I encountered the same thing, solved it with this https://github.com/jaredreich/pell/issues/123

**Comment by jacquesbh** [comment]
This issue happens when we add some texts, and remove the end of line.
Does that on Chrome, apparently not on Firefox.

![pell](https://user-images.githubusercontent.com/858611/108186768-145c3480-710e-11eb-9517-5dab8f4ac0ef.gif)

It doesn't even happen when we copy/paste some text.

This issue is probably related to the browser, but still.

**Comment by jacquesbh** [comment]
The solution we found to avoid the problem is to force some styles on the elements inside the `contenteditable` using CSS, like this:

```css
.pell-content p {
    font-size: unset !important;
}
```

This way the span tags don't appear anymore.
