### ISSUE TITLE
Cursor Control?

### ISSUE THREAD

**Issue by AsishRaju** [jaredreich/pell#202]
i inserted some text through this `editor.content.innerHTML = 'inserted some text'`, but my cursor is not moving to the end of the line , its at the starting position.

![Annotation 2020-05-14 153116](https://user-images.githubusercontent.com/41658324/81921282-fc440b80-95f7-11ea-972a-d0aa6ba711a9.png)

is there any fix ?

**Comment by AnielloFalcone** [comment]
Yes, you should manually set the caret position after inserting it with `editor.content.innerHTML` since it's not an action made within the editor. Look at issues already had and solved, example: https://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div

**Comment by AsishRaju** [comment]
@AnielloFalcone looked through it, but i am not able to figure out the solution , can you help me with it.
![Annotation 2020-05-14 213205](https://user-images.githubusercontent.com/41658324/81957577-65dd0d80-962a-11ea-879a-e53775d7e4e1.png)

**Comment by AsishRaju** [comment]
never mind i made a work around by emulating 'end' keypress 😄
