### ISSUE TITLE
Does it support attachting base64 image ?

### ISSUE THREAD

**Issue by quroom** [jaredreich/pell#214]
Currently I am using quilljs. 
Not only It's more heavy than pell but also it has critical problem that scrolling top while pasting long text
So I am considering to use pell editor, if I can use base64 image in this editor.

**Comment by jaredreich** [comment]
It does not, but feel free to submit a PR!

**Comment by quroom** [comment]
Thanks for answer.
Nowadays I am little bit busy.
So I will try it ASAP :)
I am happy that you ask me to send PR :)
I hope that I have time to send PR soon.

Have a nice day!
@jaredreich

**Comment by Ninja4Code** [comment]
I am someone who got fed up with quill as well.  Very heavy and I always experienced errors when trying to bundle it.  I will take a stab at the base64 image because I think it's a "gotta have" these days.

**Comment by jaredreich** [comment]
Nice work folks. The problem here is adding functionality like this to the core package would be just bloat.

That being said, it's a great idea for a custom-written action.

Rather than a PR, it's a good idea to post what you've written for your custom action here, and I can add it to some sort of "custom actions list" for people to reference in the future.

**Comment by Ninja4Code** [comment]
It's not bloat.  Takes all of about 5 lines of code.

**Comment by Ninja4Code** [comment]
Thanks, I created something very similar months ago and it's working well.  I love this rich text editor.
________________________________
