### ISSUE TITLE
what do we do about something like c++ code?

### ISSUE THREAD

**Issue by CingKong** [jaredreich/pell#73]
such as
`#include <header>`
?
its all good the time you wrote them, but when you store them somewhere and restore them back to the editor, them disappeared(they are filtered?)

**Comment by jaredreich** [comment]
Thanks for your issue. I feel like this is a rare edge case of how the browser's `contentEditable` and `execCommand` work. Try doing some investigation and see what you can come up with. Thanks!

**Comment by CingKong** [comment]
im sorry but im not a web developer, dont know these aspects
but this does not seemed to like a small issue, i tried several free/tiny WYSIWYG editors, they all have the same problem.

**Comment by zelon88** [comment]
It depends how you're saving and loading the files.

Pell alone cannot save or load files. So whatever you're using to get this data into and out of Pell might be sanitizing out certain characters. 

Lets say the wrapper you're using to save/load files with Pell was written with PHP. The developer of the wrapper would have to remove or encode the content being saved, and then rebuild/decode the data when Pell loads it again. Otherwise, if you were to create a file with pell containing.....

<?php echo 'Hello World; ?>

... The wrapper would parse (run) the data as code instead of content. This could create a major security problem. Documents could be crafted by hackers to compromise the server Pell is running on, and that would be bad.

If you had more information about the system you're using to save/load files with Pell we could offer more relevant assistance.

**Comment by CingKong** [comment]
i just insert the data grabbed from `editor.content.innerHTML` into mysql using prepare statement.
and then restore it back through assigning `editor.content.innerHTML` directly.
i tried to assign to a normal textarea, and it displays the html text correctly.
(im not a web designer, knowing a little about html and php, dont know whether these two things can be compared or not)
